#!/bin/bash
# Manual installation instructions for liboqs

echo "════════════════════════════════════════════════════════════"
echo "  📋 Manual Installation Required"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "I need sudo access to install liboqs. Please run these commands:"
echo ""
echo "1️⃣  Install cmake (if not already installed):"
echo "    sudo apt-get update"
echo "    sudo apt-get install -y cmake build-essential"
echo ""
echo "2️⃣  Build and install liboqs:"
echo "    cd security/third_party/liboqs"
echo "    mkdir -p build && cd build"
echo "    cmake -DCMAKE_INSTALL_PREFIX=/usr/local \\"
echo "          -DCMAKE_BUILD_TYPE=Release \\"
echo "          -DBUILD_SHARED_LIBS=ON \\"
echo "          -DOQS_BUILD_ONLY_LIB=ON .."
echo "    make -j\$(nproc)"
echo "    sudo make install"
echo "    sudo ldconfig"
echo ""
echo "3️⃣  Then rebuild Firefox:"
echo "    cd /home/kono/projects/cyqu/firefox-cyqu"
echo "    ./mach build"
echo ""
echo "════════════════════════════════════════════════════════════"
